### ISSUE TITLE
ba攻略报错

### ISSUE THREAD

**Issue by keqingyyds** [Cosmos01/Blue_Archive_HoshinoBot#16]
[2024-07-24 07:51:22,277 nonebot] INFO: Self: 1946419968, Message -2147476172 fr
'ba攻略 白子'
[2024-07-24 07:51:22,277 ba_wiki] INFO: Message -2147476172 triggered send_arona
.
[2024-07-24 07:51:28,239 ba_wiki] ERROR: <class 'aiocqhttp.exceptions.ActionFail
ed'> occured when send_arona handling message -2147476172.
[2024-07-24 07:51:28,239 ba_wiki] ERROR: <ActionFailed status='failed', retcode=
1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 6780}>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 2
8, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\bluearchive\ba
_wiki\__init__.py", line 128, in send_arona
    await bot.send(ev, msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed status='failed', retcode=1200,
data=None, message='发送超时', wording='发送超时', echo={'seq': 6780}>
[2024-07-24 07:51:28,255 nonebot] INFO: Message -2147476172 is ignored: Handled
by Hoshino

**Comment by keqingyyds** [comment]
使用的是
https://github.com/LLOneBot/LLOneBot
不知道和这个有没有关系

**Comment by keqingyyds** [comment]
其他插件是可以正常发送文字和图片的 包括ba抽卡等

**Comment by keqingyyds** [comment]
只有这个连个提示都没有

**Comment by keqingyyds** [comment]
[2024-07-24 17:04:01,617 nonebot] INFO: Self: 1946419968, Message -2147475885 fr
om 2771835668@[群:732321091]: 'ba攻略白子'
[2024-07-24 17:04:01,632 ba_wiki] INFO: Message -2147475885 triggered send_arona
.
[2024-07-24 17:04:07,417 ba_wiki] ERROR: <class 'aiocqhttp.exceptions.ActionFail
ed'> occured when send_arona handling message -2147475885.
[2024-07-24 17:04:07,417 ba_wiki] ERROR: <ActionFailed status='failed', retcode=
1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 6998}>
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\msghandler.py", line 2
8, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\Administrator\Desktop\HoshinoBot\hoshino\modules\bluearchive\ba
_wiki\__init__.py", line 128, in send_arona
    await bot.send(ev, msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\__init__.py", line 271, in send
    return await self.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiocqhttp\api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed status='failed', retcode=1200,
data=None, message='发送超时', wording='发送超时', echo={'seq': 6998}>
[2024-07-24 17:04:07,432 nonebot] INFO: Message -2147475885 is ignored: Handled
by Hoshino
[2024-07-24 17:04:07,886 头像表情包] INFO: Empty meme, skip
[2024-07-24 17:04:07,917 nonebot] INFO: Self: 1946419968, Message -2147475883 fr
om 2771835668@[群]: 'ba查询白子'
[2024-07-24 17:04:07,917 ba_wiki] INFO: Message -2147475883 triggered send_stude
nt_info.
[2024-07-24 17:04:18,797 nonebot] INFO: Message -2147475883 is ignored: Handled
by Hoshino

**Comment by keqingyyds** [comment]
可以访问的通
