### ISSUE TITLE
使用ba查询指令无法获取部分学生信息

### ISSUE THREAD

**Issue by Shirozu0103** [Cosmos01/Blue_Archive_HoshinoBot#3]
大佬您好，在使用“ba查询 xx”指令过程中发现部分学生的信息获取失败，具体学生和错误信息如下：
无法获取信息的学生：水日奈、水星野、春香、温泉切里诺、静子、小护士、水静子

Hoshinobot错误信息：
ERROR: <ActionFailed data=None, echo={'seq': 646}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
Traceback (most recent call last):
  File "C:\HOSHINO\HoshinoBot\hoshino\msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "C:\HOSHINO\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\calendar.py", line 168, in send_student_info
    await bot.send_group_forward_msg(group_id=ev.group_id,messages=msgs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\__init__.py", line 238, in call_action
    return await self._api.call_action(action=action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 178, in call_action
    result = await self._wsr_api.call_action(action, **params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 153, in call_action
    return _handle_api_result(await
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiocqhttp\api_impl.py", line 38, in _handle_api_result
    raise ActionFailed(result=result)
aiocqhttp.exceptions.ActionFailed: <ActionFailed data=None, echo={'seq': 646}, msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

gocq端错误信息：
[WARNING]: 合并转发(群)消息发送失败: 账号可能被风控.

**Comment by Shirozu0103** [comment]
感谢大佬解惑orz ，更新完gocqhttp后可以正常查询了！非常实用有趣的插件，维护辛苦啦！
