### ISSUE TITLE
ba来一井报错

### ISSUE THREAD

**Issue by Cathgao** [Cosmos01/Blue_Archive_HoshinoBot#4]
已经使用过更新卡池指令
```
2022-09-28 16:54:01 INFO Self: 3573362118, Message 2111837974 from ******@[群:******]: 'ba来一井'
[2022-09-28 16:54:01,994 blue_gacha] INFO: Message 2111837974 triggered gacha_200.
2022-09-28 16:54:01 INFO Message 2111837974 triggered gacha_200.
[2022-09-28 16:54:02,303 hoshino] ERROR: 缺少图片资源：./res/img\bluearchive\unit\icon_unit_1000.png
2022-09-28 16:54:02 ERROR 缺少图片资源：./res/img\bluearchive\unit\icon_unit_1000.png
[2022-09-28 16:54:02,313 chara] ERROR: File not found: ./res/img\bluearchive\unit\icon_unit_1000.png
2022-09-28 16:54:02 ERROR File not found: ./res/img\bluearchive\unit\icon_unit_1000.png
[2022-09-28 16:54:02,329 blue_gacha] ERROR: <class 'NameError'> occured when gacha_200 handling message 2111837974.
2022-09-28 16:54:02 ERROR <class 'NameError'> occured when gacha_200 handling message 2111837974.
[2022-09-28 16:54:02,351 blue_gacha] ERROR: name 'unknown_chara_icon' is not defined
Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 154, in render_icon
    pic = self.icon.open().convert('RGBA').resize((size, size), Image.LANCZOS)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\R.py", line 50, in open
    return Image.open(self.path)
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './res/img\\bluearchive\\unit\\icon_unit_1000.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\service.py", line 228, in wrapper
    return await func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\__init__.py", line 167, in gacha_200
    pics.append(chara.gen_team_pic(res[i:j], star_slot_verbose=False))
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 112, in gen_team_pic
    src = chara.render_icon(size, star_slot_verbose)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 157, in render_icon
    pic = unknown_chara_icon.convert('RGBA').resize((size, size), Image.LANCZOS)
NameError: name 'unknown_chara_icon' is not defined
2022-09-28 16:54:02 ERROR name 'unknown_chara_icon' is not defined
Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 154, in render_icon
    pic = self.icon.open().convert('RGBA').resize((size, size), Image.LANCZOS)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\R.py", line 50, in open
    return Image.open(self.path)
  File "C:\Users\gao\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 3068, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: './res/img\\bluearchive\\unit\\icon_unit_1000.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\service.py", line 228, in wrapper
    return await func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\__init__.py", line 167, in gacha_200
    pics.append(chara.gen_team_pic(res[i:j], star_slot_verbose=False))
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 112, in gen_team_pic
    src = chara.render_icon(size, star_slot_verbose)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 157, in render_icon
    pic = unknown_chara_icon.convert('RGBA').resize((size, size), Image.LANCZOS)
NameError: name 'unknown_chara_icon' is not defined
```

**Comment by Cathgao** [comment]
图片资源放到指定目录后报错变了
```
[2022-09-28 16:57:43,558 blue_gacha] ERROR: name 'gadget_star' is not defined
Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\service.py", line 228, in wrapper
    return await func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\__init__.py", line 167, in gacha_200
    pics.append(chara.gen_team_pic(res[i:j], star_slot_verbose=False))
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 112, in gen_team_pic
    src = chara.render_icon(size, star_slot_verbose)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 167, in render_icon
    s = gadget_star if self.star > i else gadget_star_dis
NameError: name 'gadget_star' is not defined
2022-09-28 16:57:43 ERROR name 'gadget_star' is not defined
Traceback (most recent call last):
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\service.py", line 228, in wrapper
    return await func(bot, event)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\__init__.py", line 167, in gacha_200
    pics.append(chara.gen_team_pic(res[i:j], star_slot_verbose=False))
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 112, in gen_team_pic
    src = chara.render_icon(size, star_slot_verbose)
  File "C:\Users\gao\Desktop\HoshinoBot\hoshino\modules\Blue_Archive_HoshinoBot\gacha\chara.py", line 167, in render_icon
    s = gadget_star if self.star > i else gadget_star_dis
NameError: name 'gadget_star' is not defined
```

**Comment by Cathgao** [comment]
重启之后生效了。但是结果里面有个没头像的，这个算正常吗？
![E3)`XBKRV1VG@}EE26$PDX](https://user-images.githubusercontent.com/21031564/192737924-a8ea8a91-7074-4f07-9022-69490c248021.PNG)

**Comment by Cathgao** [comment]
> 不正常，你试试重新使用更新卡池命令。 如果还有问题就检查头像文件夹内的图片是否有显示异常的，如果有就删除重新获取。更简单的方法就是把资源文件夹里头像全部删除重新获取

重下之后目前unit里除去无头像的一张图，一共是111个，请问全吗

**Comment by Cathgao** [comment]
好的，谢谢解疑
